version: '3'


services:
  picture.app:
    build:
      context: ./picture-app/
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080

  rest.test:
    build:
      context: ./robotframework/
      dockerfile: Dockerfile
    volumes:
      - "./robotframework/testsuite:/testsuite"
      - "./robotframework/reports:/reports"
    depends_on:
      - "picture.app"