version: '3'


services:
  picture.app:
    build:
      context: ./picture-app/
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080

  rest.test:
    build:
      context: ./robotframework/
      dockerfile: Dockerfile
    volumes:
      - "./robotframework/testsuite:/testsuite"
      - "./robotframework/reports:/reports"
    depends_on:
      - "picture.app"

  model.test:
    build:
      context: ./robomachine/
      dockerfile: Dockerfile
    volumes:
      - "./robomachine/testsuite:/testsuite"
    depends_on:
      - "picture.app"

  selenium.test:
    build:
      context: ./robotframework-selenium/
      dockerfile: Dockerfile
    volumes:
      - "./robotframework-selenium/testsuite:/testsuite"
      - "./robotframework-selenium/reports:/reports"
    depends_on:
      - "picture.app"