
FROM openjdk:8

WORKDIR /usr/src
RUN wget www.students.tut.fi/~rantan45/tie21201/spring-swagger-codegen-photoservice-v1.jar
RUN wget www.students.tut.fi/~rantan45/tie21201/spring-swagger-codegen-photoservice-v2.jar

CMD java -jar $JAR